### ISSUE TITLE
Filter Bar Button Updates

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2865]
Filter Bar styling has been bugging me for a while now so I have some proposed changes I hacked out quickly using my browser dev tools.

Here's the end result:

![ScreenShot_20200522110210.png](https://images.zenhubusercontent.com/55c8c0f14f7a08fbb7f431cd/b2dce558-dbfc-42f4-808b-719e89dac67a)

and here's a cut n paste of the changes i made to get the above:

- plz note: styles that are commented out are to be removed

```css

.ee-filter-bar {
  /* background: var(--ee-background-color); */
  /* background: var(--ee-color-blue-green); */
  /* border-bottom-color: var(--ee-color-grey-12); */
  /* border-bottom-style: solid; */
  /* border-bottom-width: 1px; */
  box-sizing: border-box;
  color: var(--ee-default-text-color);
  margin: 0 0 var(--ee-margin-big);
  padding: var(--ee-padding-tiny) 0;
}

.ee-filter-bar__main {
  display: flex;
  flex-flow: row wrap;
  align-items: flex-start;
  /* margin-left: calc(var(--ee-padding-tiny) * -1); */
}

.ee-filter-bar__btn-wrap {
  /* width: 100px; */
}

.ee-filter-bar__btn-wrap + .ee-filter-bar__btn-wrap {
  margin-left: var(--ee-margin-default);
}



.ee-btn-base.ee-btn {
  background: var(--ee-background-color);
  border: 2px solid var(--ee-border-color);
  /* border-color: var(--ee-color-grey-14) var(--ee-color-grey-14) var(--ee-color-grey-15); */
  border-radius: var( --ee-border-radius-small);
  /* box-shadow: var(--ee-box-shadow-tiny); */
  color: var(--ee-default-text-color);
  display: inline-flex;
  font-family: 'Segoe UI', Candara, 'Bitstream Vera Sans', 'DejaVu Sans', 'Bitstream Vera Sans', 'Trebuchet MS', Verdana, 'Verdana Ref', sans-serif;
  font-size: var( --ee-font-size-default);
  /* font-weight: bold; */
  line-height: var( --ee-font-size-default);
  /* margin: var( --ee-margin-nano) var(--ee-margin-nano) var(--ee-margin-smaller); */
  outline: none !important;
  padding: var( --ee-padding-tiny) var(--ee-padding-smaller);
  position: relative;
  text-decoration: none;
  text-align: center;
  text-shadow: var( --ee-text-shadow-inset-light);
  transition: border-color 0.1s ease 0.1s, color 0.1s ease 0.1s !important;
  vertical-align: middle;

  /* the following is new that I added around the button text - if our button component already adds a text wrapper, then just use that */
	span {
		  margin: 0 var(--ee-margin-micro) 0 var(--ee-margin-smaller);
	}
}

.btn-hover, .ee-btn-base:hover, .ee-btn-base.ee-btn:hover {
  border: 2px solid var(--ee-color-primary-low-contrast);
  color: var(--ee-color-primary);
  box-shadow: 0 0 0 1px var(--ee-color-primary-low-contrast);
}

.ee-btn-base.ee-btn.ee-filter-bar__btn--active {
  border-color: var(--ee-color-primary);
  background: var(--ee-color-primary);
  color: var(--ee-text-on-primary);
  text-shadow: none;
}


.ee-btn-base.ee-btn--small {
  font-size: var(--ee-font-size-small);
  min-height: var(--ee-font-size-small);
  line-height: var(--ee-font-size-tiny);
  padding: var(--ee-padding-nano) var(--ee-padding-smaller);
  letter-spacing: 1px;
}


.ee-svg {
  display: inline-flex;
  /* margin: 0 var(--ee-margin-micro); */
	
	path {
		fill: currentColor;
	}
}

.ee-entity-pagination {
  display: flex;
  flex-flow: row nowrap;
  justify-content: flex-end;
  padding: var(--ee-padding-huge) 0;
}

.ee-pagination {
	display: flex;
	flex-direction: row;
	padding: 1rem 0;
}

```

the above will need to be tweaked and fixed for mobile, especially the filter bar button layout container flex flow

**! Important ! **

plz try to make styles as consistent as possible across components, so if the above changes suddenly conflict with how something is displayed inside another component, then tweak things so that they match better. Talk to me first is you are unsure of anything or want confirmation before making some change (although I don't want to micromanage cuz that's no fun)

**Comment by tn3rb** [comment]
also considering this for the default button styles:

![ScreenShot_20200522124007](https://user-images.githubusercontent.com/1751030/82703857-63317800-9c29-11ea-8838-55810de3afb0.png)

```css
.ee-btn-base.ee-btn {
  background: var(--ee-color-grey-11);
  border: 2px solid var(--ee-color-grey-11);
  /* border-color: var(--ee-color-grey-14) var(--ee-color-grey-14) var(--ee-color-grey-15); */
  border-radius: var( --ee-border-radius-small);
  /* box-shadow: var(--ee-box-shadow-tiny); */
  color: var(--ee-text-on-grey-8);
  display: inline-flex;
  font-family: 'Segoe UI', Candara, 'Bitstream Vera Sans', 'DejaVu Sans', 'Bitstream Vera Sans', 'Trebuchet MS', Verdana, 'Verdana Ref', sans-serif;
  font-size: var( --ee-font-size-default);
  /* font-weight: bold; */
  line-height: var( --ee-font-size-default);
  /* margin: var( --ee-margin-nano) var(--ee-margin-nano) var(--ee-margin-smaller); */
  outline: none !important;
  padding: var( --ee-padding-tiny) var(--ee-padding-smaller);
  position: relative;
  text-decoration: none;
  text-align: center;
  text-shadow: var( --ee-text-shadow-inset-light);
  transition: border-color 0.1s ease 0.1s, color 0.1s ease 0.1s !important;
  vertical-align: middle;
}

.btn-hover, .ee-btn-base:hover, .ee-btn-base.ee-btn:hover {
  border: 2px solid var(--ee-color-primary-low-contrast);
  color: var(--ee-text-on-grey-8);
  box-shadow: 0 0 0 1px var(--ee-color-primary-low-contrast);
  background: var(--ee-color-grey-12);
}
```

but am curious to see what you could come up with and/or suggest for a good default button style that blends harmoniously with everything else we have going on

**Comment by nicolad** [comment]
heads up: changing `ee-btn-base.ee-btn` will affect other buttons' styles, do we want to have the style from fitler btns applied to all other ones?


![image](https://user-images.githubusercontent.com/1477453/82705173-d239bb80-9c7f-11ea-8d06-b5506884953f.png)

**Comment by tn3rb** [comment]
Let's also add some kind of "big" modifier to these buttons at the bottom of the entity lists (do so via button props though plz)

![ScreenShot_20200522125313](https://user-images.githubusercontent.com/1751030/82704813-38482380-9c2b-11ea-9005-2c4f7d7ea52b.png)


and maybe see if you can come up with some other way to make these a tiny bit more prominent while still matching and blending with other styles and without being garish or anything.

maybe something like:

![ScreenShot_20200522130344](https://user-images.githubusercontent.com/1751030/82705585-beb13500-9c2c-11ea-87b0-b3d72fa5a61a.png)

but I'm open to other suggestions

**Comment by tn3rb** [comment]
re:
> do we want to have the style from fitler btns applied to all other ones?

ya that drop shadow doesn't look go with the other styles we have, which have all transitioned to being more of a flat design

i think the upcoming trends will move away from flat design, but I don't know if EE users are ready for that

**Comment by tn3rb** [comment]
more button fix suggestions after fixing some things in master:

```css
.ee-btn-base.ee-btn--accent:not([disabled]) {
  background: var(--ee-background-color);
  border-color: var(--ee-color-accent);
  color: var(--ee-color-accent);
  text-shadow: none;
}

.ee-btn-base.ee-btn--accent:hover:not([disabled]) {
  background: var(--ee-color-accent);
  color: var(--ee-text-on-accent);
  box-shadow: 0 0 0 1px var(--ee-color-accent);
}
```
