### ISSUE TITLE
Use Flexbox to Improve Ticket Selector Date Selector Button Layout

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3229]
#### steps to reproduce issue

- activate following theme: Total v1.2.49 By Hash Themes

- go to frontend events list

- look at Date Selector button above Ticket Selector 👀

this theme hardcoded a button height of `40px` which prevents the content of the above button from fitting properly. The following CSS changes can fix the issue and likely improve layout across the board:

```css
.checkbox-dropdown-selector-btn {
    cursor: pointer;
    display: inline-flex;
    margin: 0 0 1em;
    min-width: 220px;
    /* padding: 1em 0; */
    position: relative;
    width: auto;
    align-items: center;
    justify-content: space-between;
}
span.checkbox-dropdown-selector-selected-spn {
    display: inline-flex;
    align-items: center;
}
span.checkbox-dropdown-selector-selected-spn .dashicons-calendar-alt {
    top: -1px;
    position: relative;
}
.checkbox-dropdown-selector-btn .dashicons-arrow-down {
    margin: 0 0 0 auto;
}
```
